port: 8001
auth:
  github-oauth-id:
  github-oauth-secret:
mongodb:
  host: 'localhost'
  port: 27017
  db: 'pulsar'
pulsar:
  repo: ''
  branch: ''
ssl:
  key: './bin/ssl/*.pulsar.local.key'
  cert: './bin/ssl/*.pulsar.local.pem'
  pfx:
  passphrase:
