default:
  port: 8001
  log:
    dir: '.'
    name: 'pulsar-rest-api.log'
  auth:
    github-oauth-id:
    guthub-oauth-secret:
  mongodb:
    host: 'localhost'
    port: 27018
    db: 'pulsar'
  pulsar:
    repo: ''
    branch: ''
  ssl:
    key: './bin/ssl/*.pulsar.local.key'
    cert: './bin/ssl/*.pulsar.local.pem'
    pfx:
    passphrase:
