port: 8001
log:
  path: './pulsar-rest-api.log'
auth:
  githubOauthId:
  githubOauthSecret:
  githubOrg:
  baseUrl:
  callbackUrl:
mongodb:
  host: 'localhost'
  port: 27017
  db: 'pulsar'
pulsar:
  repo: ''
  branch: ''
ssl:
  key: './bin/ssl/*.pulsar.local.key'
  cert: './bin/ssl/*.pulsar.local.pem'
  pfx:
  passphrase:
