version: '3.3'
services:
  api:
    build: .
    image: cargomedia/pulsar-rest-api:latest
    command: test
    volumes:
      - ./lib:/app/lib:rw,cached
      - ./test:/app/test:rw,cached
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    command: "--config /mongo/config/mongod.conf"
    volumes:
      - data-mongo:/data/db
      - ./docker/config/mongo:/mongo/config
    ports:
      - "27017:27017"

volumes:
  data-mongo:

