version: '3.2'
services:
  api:
    build: .
    image: cargomedia/pulsar-rest-api:latest
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    command: "--config /mongo/config/mongod.conf"
    volumes:
      - data-mongo:/data/db
      - ./docker/config/mongo:/mongo/config
    ports:
      - "27017:27017"

volumes:
  data-mongo:

